include ':app'
include ':capacitor-android'
project(':capacitor-android').projectDir = new File(rootProject.projectDir, '../node_modules/@capacitor/android/capacitor')
include ':capacitor-media-pipe'
project(':capacitor-media-pipe').projectDir = new File(rootProject.projectDir, 'src/main/java/io/boazblake/liftmate/capacitormediapipe')
